name: Build and Push Docker image

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Type of version bump: major, minor, or build'
        required: true
        default: 'build'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Bump version and push tag
      id: bump_version
      uses: rlespinasse/github-tag-action@v1.1.0
      with:
        release: true
        release_branches: 'main'
        default_bump: ${{ github.event.inputs.bump }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slackvectorx:${{ steps.bump_version.outputs.new_tag }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        release_name: Release ${{ steps.bump_version.outputs.new_tag }}
        draft: false
        prerelease: false
